<a href="https://colab.research.google.com/github/annsandra98/Data-Analytics/blob/master/pca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
A = array([[1, 1], [2, 1], [2, 2],[3,2]])
print(A)


[[1 1]
 [2 1]
 [2 2]
 [3 2]]


In [4]:
# calculate the mean of each column
M = mean(A.T, axis=1)
print(M)


[2.  1.5]


In [5]:
# center columns by subtracting column means
C = A - M
print(C)


[[-1.  -0.5]
 [ 0.  -0.5]
 [ 0.   0.5]
 [ 1.   0.5]]


In [6]:
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)


[[0.66666667 0.33333333]
 [0.33333333 0.33333333]]


In [7]:
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)


[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


In [8]:
print(values)


[0.872678 0.127322]


In [9]:
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[-1.11351636  0.10040571]
 [-0.26286556 -0.4253254 ]
 [ 0.26286556  0.4253254 ]
 [ 1.11351636 -0.10040571]]


In [13]:
from pandas.plotting import scatter_matrix
A = array([[1, 1], [2, 1], [2, 2],[3,2]])
df = pd.DataFrame(A, columns = ['a', 'b', 'c', 'd'])
scatter_matrix(df, alpha = 0.2, figsize = (6, 6), diagonal = 'kde')

ValueError: ignored